### ISSUE TITLE
Consider adding package-lock.json or yarn.lock

### ISSUE THREAD

**Issue by birros** [beenotung/ts-liveview#1]
The addition of package-lock.json or yarn.lock will improve the reproducibility of the build and therefore greater stability for future developments. It's commonly applied in large frameworks as React, Vue or Angular.

PS, thanks for sharing this project, the concept behind Phoenix LiveView is promising. Nice to see a beginning of implementation in TypeScript, I'm curious to see how far this concept can go.

**Comment by beenotung** [comment]
I prefer not to lock the package versions to allow installing compatible updated versions for security / performance enhancement.

If it turns out some involved package updates don't follow semver, we can narrow down the version range in package.json by not using '^' (which allows minor version updates), e.g. to use '~' (which only allows patch version updates) or to specify exact version without any prefix symbol (e.g. `"lib-name": "1.2.3"`)

For project that demand more secure setup, they can remove the lock file from `.gitignore` then include the lock file for their CI/CD workflow.

In the current version, only `pnpm-lock.yaml` is ignored, so if you use the started template with npm or yarn, the lock file could be included in your git distribution once you installed the packages.

**Comment by birros** [comment]
Thanks for the answer, the arguments are relevant.

I close the issue.

**Comment by beenotung** [comment]
thanks for raising out your concern anyway : )
