### ISSUE TITLE
Question: What does ts-liveview compare to LiveviewJs?

### ISSUE THREAD

**Issue by alexbezhan** [beenotung/ts-liveview#16]
Hi, I'm picking a LiveView implementation for my project.
What is your honest comparison of pros and cons between TS-LiveView and LiveViewJs?

**Comment by beenotung** [comment]
**How liveviewjs works:**
I do not have deep understanding on liveviewjs, from what I know, liveviewjs stays closer to the Pheonix Liveview. It maintains a copy of static array and dynamic array for each component.
When the state is changed, it re-run the rendering method, then compares the dynamic parts.
The changed parts are sent to the client to reconsolidate the view.

**How ts-liveview works:**
ts-liveview adopted similar design initially (in v0) but evolved to adopt JSX and explicit dom updates with developer specified querySelector since v2.
These changes enables html escape by default and allow more flexible state management.

**When to use which one:**
If you want to put less effort and use declarative UI with realtime updates out-of-the-box, liveviewjs may be a better fit.
If you want to use a customized state management approach with less memory and CPU consumption, ts-liveview may be a better fit?

ts-liveview also comes with realtime updates out-of-the-box on whole page level. By using the explicit update approach (opt-in), you can refine the dom updates in fine grain but you need to be careful to not miss related portions.
So I only use explicit updates with I really need to minimize the updates for low latency updates.

If you're new to liveviews, I suggest you try out both approaches to find out which one is more suitable to your case.

Thank you for your interest, follow up questions are welcomed.

**Comment by beenotung** [comment]
You may have a look at the [changelog](https://github.com/beenotung/ts-liveview/blob/master/CHANGELOG.md) of this project to see how it evolved overtime

**Comment by beenotung** [comment]
Regarding event handling, ts-liveview use html attributes, e.g. onclick, while liveviewjs follows Phoenix liveview to use custom attribute, e.g. phx-click. Which incurs some learning overhead IMO. Here is a list of event binding used in liveviewjs:
https://www.liveviewjs.com/docs/user-events-slash-bindings/bindings-table

**Comment by beenotung** [comment]
Some features that are available in ts-liveview (and not sure it they are available in liveviewjs):
1. Per-route async loading, with SEO metadata support
2. HTML streaming for initial GET request

**Comment by beenotung** [comment]
A final difference:
ts-liveview is provided as a template (rather than a library), hence any part can be modified to suit your need.

In another word, ts-liveview should feel less like a blackbox than liveviewjs. It should be easier to be extended for each applications IMHO because each project are effective a fork of the demo template.

**Comment by alexbezhan** [comment]
@beenotung cool, thank you very much for detailed overview.
I'm gonna try both and see which one fits better.
